optimizer : {
  type: AdamW,
  kwargs: {
  lr : 0.0005, 
  weight_decay : 0.05
}}

scheduler: {
  type: CosLR,
  kwargs: {
    epochs: 150,
    initial_epochs : 5
}}

# dataset : {
#   train : { _base_: cfgs/dataset_configs/ModelNet40.yaml, 
#             others: {subset: 'train'}},
#   val : { _base_: cfgs/dataset_configs/ModelNet40.yaml, 
#             others: {subset: 'test'}},
#   test : { _base_: cfgs/dataset_configs/ModelNet40.yaml, 
#             others: {subset: 'test'}}}
model : {
  # NAME: PointTransformer,
  # trans_dim: 384, 
  # depth: 12, 
  # drop_path_rate: 0.1, 
  # cls_dim: 10, 
  # num_heads: 6,
  # group_size: 32, 
  # num_group: 64, 
  # encoder_dims: 256,
  # encoder_type: 'Encoder',
  dropout: 0.5,
  # model: PointTransformer,
  num_point: 1024,
  nneighbor: 16,
  nblocks: 4,
  transformer_dim: 512,
  num_class: 10,
  input_dim: 3
}
npoints: 1024
total_bs : 32
step_per_update : 1
max_epoch : 300
grad_norm_clip : 10
consider_metric: CDL1